#!/usr/bin/env bash

if [ -f /usr/bin/subl ]; then
    export EDITOR='subl -w';
elif [ -e /usr/bin/kate ]; then
    export EDITOR='kate -b';
elif [ -e /usr/bin/nvim ]; then
    export EDITOR='nvim';
else
    export EDITOR='vi';
fi

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
export GPG_TTY=$(tty);

# Define my gpg key as KEYID
export KEYID=5FC8FE1141FA769594E91E48F41BDBF6171A3BB4
export SHORTKEYID=0xF41BDBF6171A3BB4
