#!/usr/bin/env bash

pathmunge () {
        if ! echo $PATH | /bin/grep -E -q "(^|:)$1($|:)" ; then
           if [ "$2" = "after" ] ; then
              PATH=$PATH:$1
           else
              PATH=$1:$PATH
           fi
        fi
}


pathmunge ~/bin
pathmunge ~/.local/share/gem/ruby/3.0.0/bin
